### ISSUE TITLE
Write a DHT11Sensor class

### ISSUE THREAD

**Issue by 1337encrypted** [1337encrypted/ESIOT-LAB#1]
# Write a class named as `DHT11Sensor` 

You need to edit `DTH11Sensor.cpp` based on `DHT11Sensor.h`
- `DHT11Sensor.h` will contain all the required header files and function prototypes.
- `DHT11Sensor.cpp` will contain the implementation of the various functions.

## `DHTSensor.cpp` instructions

1. include the dth.begin() function inside the constructor
2. while displaying the temperature and humidity use the format
`Humidity: 10 %; Temperature C: 22 °C;`

### Additional notes: 
- Try not edit the `DTH11Sensor.h` as its for reference only, its open for extension but closed for modification
- You will have to write code in the `DHT11Sensor.cpp` file
- Display only in centigrade.

#### Resources 
[Ralph S Bacon: How to create an Arduino Library](https://www.youtube.com/watch?v=fE3Dw0slhIc)
[Paul Mcworter: How to Connect and Use the DHT11 Temperature and Humidity Sensor ](https://www.youtube.com/watch?v=-AvF2TsB2GI)

**Comment by srushtim-01** [comment]
Implemented the DHT11Sensor
