### ISSUE TITLE
Write a buzzer class

### ISSUE THREAD

**Issue by 1337encrypted** [1337encrypted/ESIOT-LAB#2]
# Write a class named as buzzer

You need to edit `buzzer.cpp` based on `buzzer.h`

`buzzer.h` will contain all the required header files and function prototypes.
`buzzer.cpp` will contain the implementation of the various functions.

## `buzzer.cpp` instructions.  

- pinMode should be done inside the `begin()` method
- include the `begin()` method inside the constructor.  
- Use the tone library instead of `analogWrite()`
- while displaying the state of buzzer use the format.  

```
buzzer: ON;
buzzer: OFF;
```

### Additional notes:

Try not edit the buzzer.h as its for reference only, its open for extension but closed for modification
You will have to write code in the buzzer.cpp file.

#### Resources

[An easy way to make noise with Arduino using tone()](https://www.youtube.com/watch?v=1_LMAgO14z0)
[Ralph S Bacon: How to create an Arduino Library](https://www.youtube.com/watch?v=fE3Dw0slhIc)

**Comment by shradhapatil22** [comment]
Added buzzer.h and buzzer.cpp with necessary functions
